### ISSUE TITLE
Http requests possible from within javascript

### ISSUE THREAD

**Issue by mochar** [openwebf/mercury#31]
I am using a js library that sends http requests, but it is failing. (All the info I get from the library is that the requests was rejected with status 0.)

Am I supposed to implement `HttpClientInterceptor` and handle this logic from within dart myself?

Thanks!

**Comment by MulverineX** [comment]
Ellis did direct testing with `fetch` in the latest release and it's completely functional. Without more info about the library internals we probably can't help you. What is the library you're trying to use, and could you test whether regular `fetch` works in your environment?

**Comment by MulverineX** [comment]
@mochar

**Comment by mochar** [comment]
@MulverineX Thanks for the quick response again. You are right, a simple fetch response works fine. I remember now I had to rewrite a bunch of the library code to make it work with flutter_js, which is what I was using before. I will have to look at that again. Thanks so much!
